services:
  - type: web
    name: opens
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "run:app" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        value: 8baa1e03a7abd620ad3a2d4919a784803327d6f0
      - key: JWT_SECRET_KEY
        value: 6718e13e2a7a2d4919a784803327d6f0
      - key: DATABASE_URL
        value: postgres://user:password@hostname:5432/dbname
